# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-27 19:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advs',
            name='view',
            field=models.IntegerField(default=0, verbose_name='\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u043e\u0432'),
        ),
    ]
